name: Weekly Paper Bot

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      # v3에서 v4로 업데이트 (Node.js 최신 버전 지원)
      - uses: actions/checkout@v4 
      
      # v4에서 v5로 업데이트 (Node.js 최신 버전 지원)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          pip install scholarly google-generativeai requests
      - name: Run Python script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          ZOTERO_API_KEY: ${{ secrets.ZOTERO_API_KEY }}
          ZOTERO_USER_ID: ${{ secrets.ZOTERO_USER_ID }}
        run: python paper_bot.py
